# Generated by Django 2.2.14 on 2020-08-28 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20200710_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=610, verbose_name='Enter Message')),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('Post Rank', 'Post Rank'), ('Post Comment', 'Post Comment')], max_length=16, verbose_name='Select Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_auther_set', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_post_set', to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Management',
                'verbose_name_plural': 'Notification Management',
            },
        ),
    ]
