# Generated by Django 2.2.16 on 2020-09-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Post Rank', 'Post Rank'), ('Post Comment', 'Post Comment'), ('Group Joining Request', 'Group Joining Request'), ('Group Invite', 'Group Invite')], max_length=16, verbose_name='Select Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_post_set', to='posts.Post'),
        ),
    ]
