# Generated by Django 2.2.16 on 2020-09-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200915_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Post Rank', 'Post Rank'), ('Post Comment', 'Post Comment'), ('Group Joining Request', 'Group Joining Request'), ('Group Invite', 'Group Invite')], max_length=30, verbose_name='Select Type'),
        ),
    ]
