export const CREATE_GROUP_REQUEST = 'GROUP/CREATE_GROUP/REQUEST';
export const CREATE_GROUP_SUCCESS = 'GROUP/CREATE_GROUP/SUCCESS';
export const CREATE_GROUP_ERROR = 'GROUP/CREATE_GROUP/ERROR';
export const SET_DEFAULT_SUCCESS_REQUEST = 'GROUP/SET_DEFAULT_SUCCESS/REQUEST';
export const SET_DEFAULT_SUCCESS_SUCCESS = 'GROUP/SET_DEFAULT_SUCCESS/SUCCESS';
export const SET_DEFAULT_SUCCESS_ERROR = 'GROUP/SET_DEFAULT_SUCCESS/ERROR';
