# Generated by Django 2.2.14 on 2020-09-05 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200710_1643'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoiningRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joining_request_group', to='groups.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joining_request_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Joining Request Management',
                'verbose_name_plural': 'Group Joining Management',
            },
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post_group_set', to='groups.Group')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post_set', to='posts.Post')),
            ],
            options={
                'verbose_name': 'Group Post Management',
                'verbose_name_plural': 'Group Post Management',
            },
        ),
    ]
