# Generated by Django 2.2.14 on 2020-09-05 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_grouppost_joiningrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_user_group', to='groups.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_user_user_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Invite Management',
                'verbose_name_plural': 'Group Invite Management',
            },
        ),
    ]
