export const EMAIL_AUTH_SIGNUP_REQUEST = 'EMAIL_AUTH/SIGNUP/REQUEST';
export const EMAIL_AUTH_SIGNUP_SUCCESS = 'EMAIL_AUTH/SIGNUP/SUCCESS';
export const EMAIL_AUTH_SIGNUP_ERROR = 'EMAIL_AUTH/SIGNUP/ERROR';

export const EMAIL_AUTH_LOGIN_REQUEST = 'EMAIL_AUTH/LOGIN/REQUEST';
export const EMAIL_AUTH_LOGIN_SUCCESS = 'EMAIL_AUTH/LOGIN/SUCCESS';
export const EMAIL_AUTH_LOGIN_ERROR = 'EMAIL_AUTH/LOGIN/ERROR';

// does not follow the patern REQUERST/SUCCESS/ERROR since it is syncronus action
export const EMAIL_AUTH_LOGOUT_REQUEST = 'EMAIL_AUTH/LOGOUT/REQUEST';
export const EMAIL_AUTH_LOGOUT_SUCCESS = 'EMAIL_AUTH/LOGOUT/SUCCESS';
export const EMAIL_AUTH_LOGOUT_ERROR = 'EMAIL_AUTH/LOGOUT/ERROR';

export const EMAIL_AUTH_PASSWORD_RECOVER_REQUEST =
  'EMAIL_AUTH/PASSORD_RECOVER/REQUEST';
export const EMAIL_AUTH_PASSWORD_RECOVER_SUCCESS =
  'EMAIL_AUTH/PASSORD_RECOVER/SUCCESS';
export const EMAIL_AUTH_PASSWORD_RECOVER_ERROR =
  'EMAIL_AUTH/PASSORD_RECOVER/ERROR';
export const EMAIL_AUTH_FORGOT_PASSWORD_REQUEST =
  'EMAIL_AUTH/FORGOT_PASSWORD/REQUEST';
export const EMAIL_AUTH_FORGOT_PASSWORD_SUCCESS =
  'EMAIL_AUTH/FORGOT_PASSWORD/SUCCESS';
export const EMAIL_AUTH_FORGOT_PASSWORD_ERROR =
  'EMAIL_AUTH/FORGOT_PASSWORD/ERROR';
export const EMAIL_AUTH_RESET_PASSWORD_REQUEST =
  'EMAIL_AUTH/RESET_PASSWORD/REQUEST';
export const EMAIL_AUTH_RESET_PASSWORD_SUCCESS =
  'EMAIL_AUTH/RESET_PASSWORD/SUCCESS';
export const EMAIL_AUTH_RESET_PASSWORD_ERROR =
  'EMAIL_AUTH/RESET_PASSWORD/ERROR';
export const EMAIL_AUTH_CONFIRM_CODE_REQUEST =
  'EMAIL_AUTH/CONFIRM_CODE/REQUEST';
export const EMAIL_AUTH_CONFIRM_CODE_SUCCESS =
  'EMAIL_AUTH/CONFIRM_CODE/SUCCESS';
export const EMAIL_AUTH_CONFIRM_CODE_ERROR = 'EMAIL_AUTH/CONFIRM_CODE/ERROR';
export const EMAIL_AUTH_RESEND_CODE_REQUEST = 'EMAIL_AUTH/RESEND_CODE/REQUEST';
export const EMAIL_AUTH_RESEND_CODE_SUCCESS = 'EMAIL_AUTH/RESEND_CODE/SUCCESS';
export const EMAIL_AUTH_RESEND_CODE_ERROR = 'EMAIL_AUTH/RESEND_CODE/ERROR';
