export const PROFILE_USER_DETAIL_REQUEST = 'PROFILE/USER_DETAIL/REQUEST';
export const PROFILE_USER_DETAIL_SUCCESS = 'PROFILE/USER_DETAIL/SUCCESS';
export const PROFILE_USER_DETAIL_ERROR = 'PROFILE/USER_DETAIL/ERROR';
export const PROFILE_FOLLOWERS_CONNECTIONS_LIST_REQUEST =
  'PROFILE/FOLLOWERS_CONNECTIONS_LIST/REQUEST';
export const PROFILE_FOLLOWERS_CONNECTIONS_LIST_SUCCESS =
  'PROFILE/FOLLOWERS_CONNECTIONS_LIST/SUCCESS';
export const PROFILE_FOLLOWERS_CONNECTIONS_LIST_ERROR =
  'PROFILE/FOLLOWERS_CONNECTIONS_LIST/ERROR';
export const PROFILE_FOLLOWING_CONNECTIONS_LIST_REQUEST =
  'PROFILE/FOLLOWING_CONNECTIONS_LIST/REQUEST';
export const PROFILE_FOLLOWING_CONNECTIONS_LIST_SUCCESS =
  'PROFILE/FOLLOWING_CONNECTIONS_LIST/SUCCESS';
export const PROFILE_FOLLOWING_CONNECTIONS_LIST_ERROR =
  'PROFILE/FOLLOWING_CONNECTIONS_LIST/ERROR';
export const FOLLOW_USER_REQUEST = 'PROFILE/FOLLOW_USER/REQUEST';
export const FOLLOW_USER_SUCCESS = 'PROFILE/FOLLOW_USER/SUCCESS';
export const FOLLOW_USER_ERROR = 'PROFILE/FOLLOW_USER/ERROR';
export const UNFOLLOW_USER_REQUEST = 'PROFILE/UNFOLLOW_USER/REQUEST';
export const UNFOLLOW_USER_SUCCESS = 'PROFILE/UNFOLLOW_USER/SUCCESS';
export const UNFOLLOW_USER_ERROR = 'PROFILE/UNFOLLOW_USER/ERROR';
export const PROFILE_SEARCH_FOLLOWERS_CONNECTIONS_LIST_REQUEST =
  'PROFILE/SEARCH_FOLLOWERS_CONNECTIONS_LIST/REQUEST';
export const PROFILE_SEARCH_FOLLOWERS_CONNECTIONS_LIST_SUCCESS =
  'PROFILE/SEARCH_FOLLOWERS_CONNECTIONS_LIST/SUCCESS';
export const PROFILE_SEARCH_FOLLOWERS_CONNECTIONS_LIST_ERROR =
  'PROFILE/SEARCH_FOLLOWERS_CONNECTIONS_LIST/ERROR';
export const PROFILE_SEARCH_FOLLOWING_CONNECTIONS_LIST_REQUEST =
  'PROFILE/SEARCH_FOLLOWING_CONNECTIONS_LIST/REQUEST';
export const PROFILE_SEARCH_FOLLOWING_CONNECTIONS_LIST_SUCCESS =
  'PROFILE/SEARCH_FOLLOWING_CONNECTIONS_LIST/SUCCESS';
export const PROFILE_SEARCH_FOLLOWING_CONNECTIONS_LIST_ERROR =
  'PROFILE/SEARCH_FOLLOWING_CONNECTIONS_LIST/ERROR';
export const CHANGE_PASSWORD_REQUEST = 'PROFILE/CHANGE_PASSWORD/REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'PROFILE/CHANGE_PASSWORD/SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'PROFILE/CHANGE_PASSWORD/ERROR';
export const EDIT_PROFILE_REQUEST = 'PROFILE/EDIT_PROFILE/REQUEST';
export const EDIT_PROFILE_SUCCESS = 'PROFILE/EDIT_PROFILE/SUCCESS';
export const EDIT_PROFILE_ERROR = 'PROFILE/EDIT_PROFILE/ERROR';
export const INVITE_USER_TO_GROUP_REQUEST = 'PROFILE/INVITE_USER_TO_GROUP/REQUEST';
export const INVITE_USER_TO_GROUP_SUCCESS = 'PROFILE/INVITE_USER_TO_GROUP/SUCCESS';
export const INVITE_USER_TO_GROUP_ERROR = 'PROFILE/INVITE_USER_TO_GROUP/ERROR';
export const GET_NOTIFICATIONS_REQUEST = 'PROFILE/GET_NOTIFICATIONS/REQUEST';
export const GET_NOTIFICATIONS_SUCCESS = 'PROFILE/GET_NOTIFICATIONS/SUCCESS';
export const GET_NOTIFICATIONS_ERROR = 'PROFILE/GET_NOTIFICATIONS/ERROR';
export const READ_NOTIFICATION_REQUEST = 'PROFILE/READ_NOTIFICATION/REQUEST';
export const READ_NOTIFICATION_SUCCESS = 'PROFILE/READ_NOTIFICATION/SUCCESS';
export const READ_NOTIFICATION_ERROR = 'PROFILE/READ_NOTIFICATION/ERROR';
export const ACCEPT_GROUP_JOIN_REQUEST = 'PROFILE/ACCEPT_GROUP_JOIN/REQUEST';
export const ACCEPT_GROUP_JOIN_SUCCESS = 'PROFILE/ACCEPT_GROUP_JOIN/SUCCESS';
export const ACCEPT_GROUP_JOIN_ERROR = 'PROFILE/ACCEPT_GROUP_JOIN/ERROR';
export const ACCEPT_GROUP_INVITE_REQUEST = 'PROFILE/ACCEPT_GROUP_INVITE/REQUEST';
export const ACCEPT_GROUP_INVITE_SUCCESS = 'PROFILE/ACCEPT_GROUP_INVITE/SUCCESS';
export const ACCEPT_GROUP_INVITE_ERROR = 'PROFILE/ACCEPT_GROUP_INVITE/ERROR';
export const PROFILE_USER_DETAIL_LOADING = 'PROFILE/USER_DETAIL/LOADING';
