# Generated by Django 2.2.14 on 2020-07-29 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='chat_images/', verbose_name='Chat Media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_image_user_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Media Management',
                'verbose_name_plural': 'Chat Media Management',
                'ordering': ('created_at',),
            },
        ),
    ]
