# Generated by Django 2.2.13 on 2020-06-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200601_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='Enter Caption for post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(upload_to='posts/', verbose_name='SELECT Media'),
        ),
    ]
