# Generated by Django 2.2.13 on 2020-06-15 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20200615_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Enter Rank')),
                ('average_rank', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Enter Average Rank')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_rank_post', to='posts.Post')),
                ('ranker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_rank_ranker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Rank Management',
                'verbose_name_plural': 'Post Rank Management',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Enter Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_commenter_set', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_post_set', to='posts.Post')),
            ],
            options={
                'verbose_name': 'Post Comment Management',
                'verbose_name_plural': 'Post Comment Management',
            },
        ),
    ]
