# Generated by Django 2.2.13 on 2020-06-18 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrank',
            name='rank',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Please choose 1-5', regex='^[1-5]$')], verbose_name='Enter Rank'),
        ),
    ]
