# Generated by Django 2.2.12 on 2020-06-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_connectedsocialmedia_userdetail_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Select Gender'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='location_address',
            field=models.TextField(blank=True, null=True, verbose_name='Enter User Address'),
        ),
    ]
