# Generated by Django 2.2.13 on 2020-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200601_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Instagram Link'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Youtube Link'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('Artist', 'Artist'), ('Videographer', 'Videographer'), ('Engineer', 'Engineer'), ('Dancer', 'Dancer'), ('Producer', 'Producer'), ('DJ', 'DJ')], max_length=15, verbose_name='Select User Type'),
        ),
        migrations.DeleteModel(
            name='ConnectedSocialMedia',
        ),
    ]
