export const USER_POSTS_REQUEST = 'HOMEPAGE/USER_POSTS/REQUEST';
export const USER_POSTS_SUCCESS = 'HOMEPAGE/USER_POSTS/SUCCESS';
export const USER_POSTS_ERROR = 'HOMEPAGE/USER_POSTS/ERROR';
export const USER_POSTS_COMMENTS_REQUEST =
  'HOMEPAGE/USER_POSTS_COMMENTS/REQUEST';
export const USER_POSTS_COMMENTS_SUCCESS =
  'HOMEPAGE/USER_POSTS_COMMENTS/SUCCESS';
export const USER_POSTS_COMMENTS_ERROR = 'HOMEPAGE/USER_POSTS_COMMENTS/ERROR';
export const USER_EDIT_POST_RANK_REQUEST = 'HOMEPAGE/EDIT_POST_RANK/REQUEST';
export const USER_EDIT_POST_RANK_SUCCESS = 'HOMEPAGE/EDIT_POST_RANK/SUCCESS';
export const USER_EDIT_POST_RANK_ERROR = 'HOMEPAGE/EDIT_POST_RANK/ERROR';
export const USER_ADD_POST_VIEW_REQUEST = 'HOMEPAGE/ADD_POST_VIEW/REQUEST';
export const USER_ADD_POST_VIEW_SUCCESS = 'HOMEPAGE/ADD_POST_VIEW/SUCCESS';
export const USER_ADD_POST_VIEW_ERROR = 'HOMEPAGE/ADD_POST_VIEW/ERROR';
