export const USER_POSTS_REQUEST = 'HOMEPAGE/USER_POSTS/REQUEST';
export const USER_POSTS_SUCCESS = 'HOMEPAGE/USER_POSTS/SUCCESS';
export const USER_POSTS_ERROR = 'HOMEPAGE/USER_POSTS/ERROR';
export const USER_POSTS_COMMENTS_REQUEST =
  'HOMEPAGE/USER_POSTS_COMMENTS/REQUEST';
export const USER_POSTS_COMMENTS_SUCCESS =
  'HOMEPAGE/USER_POSTS_COMMENTS/SUCCESS';
export const USER_POSTS_COMMENTS_ERROR = 'HOMEPAGE/USER_POSTS_COMMENTS/ERROR';
export const USER_EDIT_POST_RANK_REQUEST = 'HOMEPAGE/EDIT_POST_RANK/REQUEST';
export const USER_EDIT_POST_RANK_SUCCESS = 'HOMEPAGE/EDIT_POST_RANK/SUCCESS';
export const USER_EDIT_POST_RANK_ERROR = 'HOMEPAGE/EDIT_POST_RANK/ERROR';
export const USER_ADD_POST_VIEW_REQUEST = 'HOMEPAGE/ADD_POST_VIEW/REQUEST';
export const USER_ADD_POST_VIEW_SUCCESS = 'HOMEPAGE/ADD_POST_VIEW/SUCCESS';
export const USER_ADD_POST_VIEW_ERROR = 'HOMEPAGE/ADD_POST_VIEW/ERROR';
export const USER_ADD_COMMENT_POST_REQUEST = 'HOMEPAGE/DD_COMMENT_POST/REQUEST';
export const USER_ADD_COMMENT_POST_SUCCESS = 'HOMEPAGE/DD_COMMENT_POST/SUCCESS';
export const USER_ADD_COMMENT_POST_ERROR = 'HOMEPAGE/DD_COMMENT_POST/ERROR';
export const USER_SEARCH_PERFORMIT_REQUEST =
  'HOMEPAGE/USER_SEARCH_PERFORMIT/REQUEST';
export const USER_SEARCH_PERFORMIT_SUCCESS =
  'HOMEPAGE/USER_SEARCH_PERFORMIT/SUCCESS';
export const USER_SEARCH_PERFORMIT_ERROR =
  'HOMEPAGE/USER_SEARCH_PERFORMIT/ERROR';
export const CREATE_POST_REQUEST = 'HOMEPAGE/CREATE_POST/REQUEST';
export const CREATE_POST_SUCCESS = 'HOMEPAGE/CREATE_POST/SUCCESS';
export const CREATE_POST_ERROR = 'HOMEPAGE/CREATE_POST/ERROR';
export const NEARBY_USERS_REQUEST = 'HOMEPAGE/NEARBY_USERS/REQUEST';
export const NEARBY_USERS_SUCCESS = 'HOMEPAGE/NEARBY_USERS/SUCCESS';
export const NEARBY_USERS_ERROR = 'HOMEPAGE/NEARBY_USERS/ERROR';
export const UPDATE_LOCATION_REQUEST = 'HOMEPAGE/UPDATE_LOCATION/REQUEST';
export const UPDATE_LOCATION_SUCCESS = 'HOMEPAGE/UPDATE_LOCATION/SUCCESS';
export const UPDATE_LOCATION_ERROR = 'HOMEPAGE/UPDATE_LOCATION/ERROR';
